Jbide 27520
jbosstools/jbosstools-quarkus pull request #116
Opened 2020-10-13 10:14 UTC by olkornii

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work? https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/quarkus-itests/184/

2020-10-14 09:08 UTC, jkopriva requested changes

2020-10-14 09:08 UTC, jkopriva commented on itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/RunProjectWithDebugTest.java
> +				} catch (Exception e) {
Too generic exception. Use at least RedDeerException(or maybe something more specific).

2020-10-14 09:21 UTC, olkornii commented on itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/RunProjectWithDebugTest.java
> +				} catch (Exception e) {
fixed

2020-10-15 08:46 UTC, jkopriva approved these changes

2020-10-15 08:47 UTC, merged