JBIDE-27582: reworked Quarkus test given new quarkus project
jbosstools/jbosstools-quarkus pull request #122
Opened 2021-01-06 11:38 UTC by olkornii

Signed-off-by: olkornii <olkornii@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

2021-01-06 11:39 UTC, olkornii commented
https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/quarkus-itests/313/

2021-01-13 07:40 UTC, jkopriva commented
testPR

2021-01-19 13:07 UTC, olkornii commented
Ready for merge.

2021-01-26 13:46 UTC, jkopriva requested changes

2021-01-26 13:46 UTC, jkopriva commented on itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/content/assistant/ApplicationPropertiesNewExtensionContentAssistTest.java
>  					.readFile(WORKSPACE + "/" + NEW_EXTENSION_PROJECT_NAME + "/pom.xml");
Maybe its time to move readfile function to AbstractQuarkusTest

2021-01-26 13:46 UTC, jkopriva commented on itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/RunProjectWithDebugTest.java
> +		StringBuilder bld = new StringBuilder();
please move this to AbstractTest class

2021-01-26 13:46 UTC, jkopriva commented on itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/RunProjectWithDebugTest.java
> +			new WaitUntil(new AbstractWaitCondition() {
you cannot use condition ShellIsActive?

2021-02-01 14:46 UTC, olkornii commented
test PR

2021-02-01 14:46 UTC, olkornii commented
testPR

2021-02-03 07:52 UTC, jkopriva commented on itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/universal/methods/AbstractQuarkusTest.java
> +		} catch (org.eclipse.reddeer.common.exception.WaitTimeoutExpiredException e) { // sometimes node.js warning
is this related to this issue? https://issues.redhat.com/browse/JBIDE-27432

2021-02-03 10:31 UTC, merged