Introduce GitHub Actions PR Check workflow, fixes JBIDE-27706
jbosstools/jbosstools-quarkus pull request #140
Opened 2021-03-31 11:35 UTC by odockal

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

2021-03-31 12:00 UTC, odockal commented
Successful actions run on my fork: https://github.com/odockal/jbosstools-quarkus/pull/1/checks?check_run_id=2236610843

2021-04-07 10:51 UTC, odockal commented
@sbouchet Ping, review please.

2021-04-20 13:19 UTC, sbouchet requested changes

2021-04-20 13:19 UTC, sbouchet commented on .github/workflows/build_test.yml
> +          -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true --quiet
please add --no-transfer-progress

2021-04-29 15:20 UTC, sbouchet approved these changes
LGTM

2021-04-30 12:47 UTC, merged