JBIDE-28449: Extensions from platform should have an indicator
jbosstools/jbosstools-quarkus pull request #185
Opened 2022-07-20 15:47 UTC by jeffmaury

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

2022-08-03 08:12 UTC, sbouchet requested changes

2022-08-03 08:12 UTC, sbouchet commented on plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/QuarkusUIPlugin.java
> -			      "/icon/fighter-jet-solid.png"));
icon is no more needed, please remove it from /icon folder as well

2022-08-03 08:12 UTC, sbouchet commented
also, is there any example/extension without the icon yet to test ?

2022-08-03 08:14 UTC, jeffmaury commented
> also, is there any example/extension without the icon yet to test ?

Quinoa

2022-08-04 14:08 UTC, sbouchet reviewed
LGTM, however the icon is still there ?

2022-08-04 14:31 UTC, jeffmaury commented
> LGTM, however the icon is still there ?

It should be a different icon. Previously the icon identified extensions that add sample code, now the icon identifies extensions that are part of the platform

2022-08-05 07:41 UTC, sbouchet commented
> > LGTM, however the icon is still there ?
> 
> It should be a different icon. Previously the icon identified extensions that add sample code, now the icon identifies extensions that are part of the platform

yes, i see the new icon in the UI, my remark is more that the oldone is still in the source code repo and should be deleted since it is not used anymore :)

2022-08-05 08:40 UTC, jeffmaury commented
> > > LGTM, however the icon is still there ?
> > 
> > 
> > It should be a different icon. Previously the icon identified extensions that add sample code, now the icon identifies extensions that are part of the platform
> 
> yes, i see the new icon in the UI, my remark is more that the old one is still in the source code repo and should be deleted since it is not used anymore :)

Sorry I pushed my commit to another PR. Fixed now

2022-08-08 07:51 UTC, sbouchet approved these changes
LGTM

2022-08-08 10:07 UTC, merged